/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pestpost;

import java.util.EventObject;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFileChooser;

/**
 *
 * @author wesseling
 */
public class PestPostGUI extends javax.swing.JFrame {

  /**
   * Creates new form PestPostGUI
   */
  private Control myControl;
  private Timer myTimer;
   
  public PestPostGUI() {
    initComponents();
    myControl = new Control();
    myControl.readLisemFileNames(txtDEM, txtKSat, txtThetaSat, txtThetaInit, txtInfilFile,
            txtFlowDirectionFile, txtPesticideFile, txtSurfaceStorageFile, txtSurfaceVelocityFile,
            txtSurfaceRunoffFile, txtDetachmentFile, txtPrecipitationFile, txtPrecipitationDataFile, txtTimestep);
    myControl.readOutputFileNames(txtOutputDir, txtThetaFC, txtOrderFile, txtLossesFile, txtSegmentsFile,
            chckbxDepth0, chckbxDepth1, chckbxDepth2, chckbxDepth3, chckbxDepth4, 
            chckbxDepth5, chckbxDepth6, chckbxDepth7, chckbxDepth8, chckbxDepth9, 
            txtDepth0, txtDepth1, txtDepth2, txtDepth3, txtDepth4,
            txtDepth5, txtDepth6, txtDepth7, txtDepth8, txtDepth9,
            chckbxNewArea);
    setFieldVisibility();
    myControl.readPesticideData(txtTimeSteps, txtProfileDepth, txtInitialConcentration, 
            txtAppliedConcentration, txtRetardationFactor, txtDispersionCoefficient, 
            txtDegradationCoefficient, txtHalfTime, txtMaxCw, txtMaxCs, txtInfiltrationFactor, 
            txtInitialCellContent);
    myControl.readSingleRun(txtTopConcentration, txtWaterVelocity, txtOutputFileSingleRun);
    myControl.readCoreData(txtCore, chckbxSurfaceOnly);
    myControl.addEventListener(new AddToLogEventListener());       
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
 
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jCheckBox1 = new javax.swing.JCheckBox();
    tbpnlMain = new javax.swing.JTabbedPane();
    pnlSelect = new javax.swing.JPanel();
    btnSingle = new javax.swing.JButton();
    btnLisem = new javax.swing.JButton();
    pnlLisem = new javax.swing.JPanel();
    lblKSat = new javax.swing.JLabel();
    lblThetaSat = new javax.swing.JLabel();
    lblThetaInit = new javax.swing.JLabel();
    txtThetaSat = new javax.swing.JTextField();
    txtThetaInit = new javax.swing.JTextField();
    btnKSatBrowse = new javax.swing.JButton();
    btnThetaSatBrowse = new javax.swing.JButton();
    btnThetaIniBrowse = new javax.swing.JButton();
    txtKSat = new javax.swing.JTextField();
    btnNext1 = new javax.swing.JButton();
    lblInfilFile = new javax.swing.JLabel();
    txtInfilFile = new javax.swing.JTextField();
    btnInfilFileBrowse = new javax.swing.JButton();
    lblPesticideFile = new javax.swing.JLabel();
    lblFlowDirectionFile = new javax.swing.JLabel();
    txtPesticideFile = new javax.swing.JTextField();
    txtFlowDirectionFile = new javax.swing.JTextField();
    btnPesticideFileBrowse = new javax.swing.JButton();
    btnFlowDirectionFileBrowse = new javax.swing.JButton();
    lblDEM = new javax.swing.JLabel();
    txtDEM = new javax.swing.JTextField();
    btnDEMBrowse = new javax.swing.JButton();
    lblSurfaceStorageFile = new javax.swing.JLabel();
    txtSurfaceStorageFile = new javax.swing.JTextField();
    btnSurfaceBrowse = new javax.swing.JButton();
    lblSurfaceVelocityFile = new javax.swing.JLabel();
    lblSurfaceRunoffFile = new javax.swing.JLabel();
    txtSurfaceRunoffFile = new javax.swing.JTextField();
    txtSurfaceVelocityFile = new javax.swing.JTextField();
    btnSurfaceVelocityBrowse = new javax.swing.JButton();
    btnSurfaceRunoffBrowse = new javax.swing.JButton();
    lblPreipitationFile = new javax.swing.JLabel();
    txtPrecipitationFile = new javax.swing.JTextField();
    btnPrecipitationFileBrowse = new javax.swing.JButton();
    lblPreipitationDataFile = new javax.swing.JLabel();
    txtPrecipitationDataFile = new javax.swing.JTextField();
    btnPrecipitationDataFileBrowse = new javax.swing.JButton();
    lblTimestep = new javax.swing.JLabel();
    txtTimestep = new javax.swing.JTextField();
    txtDetachmentFile = new javax.swing.JTextField();
    lblDetachmentFile = new javax.swing.JLabel();
    btnDetachmentBrowse = new javax.swing.JButton();
    pnlOut = new javax.swing.JPanel();
    lblThetaFC = new javax.swing.JLabel();
    lblOutputDir = new javax.swing.JLabel();
    lblOrder = new javax.swing.JLabel();
    chckbxNewArea = new javax.swing.JCheckBox();
    lblOutputDepths = new javax.swing.JLabel();
    chckbxDepth0 = new javax.swing.JCheckBox();
    chckbxDepth1 = new javax.swing.JCheckBox();
    chckbxDepth2 = new javax.swing.JCheckBox();
    chckbxDepth3 = new javax.swing.JCheckBox();
    chckbxDepth4 = new javax.swing.JCheckBox();
    txtDepth4 = new javax.swing.JTextField();
    txtDepth3 = new javax.swing.JTextField();
    txtDepth2 = new javax.swing.JTextField();
    txtDepth1 = new javax.swing.JTextField();
    txtDepth0 = new javax.swing.JTextField();
    lblNewArea = new javax.swing.JLabel();
    txtOrderFile = new javax.swing.JTextField();
    txtOutputDir = new javax.swing.JTextField();
    txtThetaFC = new javax.swing.JTextField();
    btnOrderFileBrowse = new javax.swing.JButton();
    btnOutputDirBrowse = new javax.swing.JButton();
    btnThetaFCBrowse = new javax.swing.JButton();
    btnNext2 = new javax.swing.JButton();
    txtDepth9 = new javax.swing.JTextField();
    txtDepth8 = new javax.swing.JTextField();
    txtDepth7 = new javax.swing.JTextField();
    txtDepth6 = new javax.swing.JTextField();
    txtDepth5 = new javax.swing.JTextField();
    chckbxDepth9 = new javax.swing.JCheckBox();
    chckbxDepth8 = new javax.swing.JCheckBox();
    chckbxDepth7 = new javax.swing.JCheckBox();
    chckbxDepth6 = new javax.swing.JCheckBox();
    chckbxDepth5 = new javax.swing.JCheckBox();
    lblLosses = new javax.swing.JLabel();
    lblSegments = new javax.swing.JLabel();
    txtLossesFile = new javax.swing.JTextField();
    txtSegmentsFile = new javax.swing.JTextField();
    btnLossesFileBrowse = new javax.swing.JButton();
    btnSegmentsFileBrowse = new javax.swing.JButton();
    pnlCore = new javax.swing.JPanel();
    lblCore = new javax.swing.JLabel();
    txtCore = new javax.swing.JTextField();
    chckbxSurfaceOnly = new javax.swing.JCheckBox();
    btnCoreBrowse = new javax.swing.JButton();
    btnNextCore = new javax.swing.JButton();
    pnlPesticide = new javax.swing.JPanel();
    btnNext3 = new javax.swing.JButton();
    lblProfileDepth = new javax.swing.JLabel();
    txtProfileDepth = new javax.swing.JTextField();
    lblInitialConcentration = new javax.swing.JLabel();
    lblAppliedConcentration = new javax.swing.JLabel();
    lblRetardataionFactor = new javax.swing.JLabel();
    lblDispersionCoefficient = new javax.swing.JLabel();
    lblDegradationCoefficient = new javax.swing.JLabel();
    txtDegradationCoefficient = new javax.swing.JTextField();
    txtDispersionCoefficient = new javax.swing.JTextField();
    txtRetardationFactor = new javax.swing.JTextField();
    txtAppliedConcentration = new javax.swing.JTextField();
    txtInitialConcentration = new javax.swing.JTextField();
    lblTimeSteps = new javax.swing.JLabel();
    txtTimeSteps = new javax.swing.JTextField();
    lblHalfTime = new javax.swing.JLabel();
    txtHalfTime = new javax.swing.JTextField();
    lblMaxCw = new javax.swing.JLabel();
    lblMaxCs = new javax.swing.JLabel();
    txtMaxCw = new javax.swing.JTextField();
    txtMaxCs = new javax.swing.JTextField();
    lblInitialCellContent = new javax.swing.JLabel();
    txtInitialCellContent = new javax.swing.JTextField();
    lblInfiltrationFactor = new javax.swing.JLabel();
    txtInfiltrationFactor = new javax.swing.JTextField();
    pnlSingleRun = new javax.swing.JPanel();
    lblWaterVelocity = new javax.swing.JLabel();
    lblTopConcentration = new javax.swing.JLabel();
    txtWaterVelocity = new javax.swing.JTextField();
    txtTopConcentration = new javax.swing.JTextField();
    lblOutputSingleRun = new javax.swing.JLabel();
    txtOutputFileSingleRun = new javax.swing.JTextField();
    btnBrowseOutputSingleRun = new javax.swing.JButton();
    btnNext5 = new javax.swing.JButton();
    pnlLog = new javax.swing.JPanel();
    scrlpnLog = new javax.swing.JScrollPane();
    txtLog = new javax.swing.JTextArea();
    lblLog = new javax.swing.JLabel();
    btnExit = new javax.swing.JButton();

    jCheckBox1.setText("jCheckBox1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Pesticide Postprocessor V0.3 (13 Sept. 2017)");
    setName("frmGUI"); // NOI18N
    setResizable(false);

    tbpnlMain.setAutoscrolls(true);

    btnSingle.setText("Make single run");
    btnSingle.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSingleActionPerformed(evt);
      }
    });

    btnLisem.setText("Run for Lisem data");
    btnLisem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLisemActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlSelectLayout = new javax.swing.GroupLayout(pnlSelect);
    pnlSelect.setLayout(pnlSelectLayout);
    pnlSelectLayout.setHorizontalGroup(
      pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectLayout.createSequentialGroup()
        .addContainerGap(78, Short.MAX_VALUE)
        .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnLisem, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(36, 36, 36))
    );
    pnlSelectLayout.setVerticalGroup(
      pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlSelectLayout.createSequentialGroup()
        .addGap(138, 138, 138)
        .addComponent(btnSingle)
        .addGap(18, 18, 18)
        .addComponent(btnLisem)
        .addContainerGap(411, Short.MAX_VALUE))
    );

    tbpnlMain.addTab("Select", pnlSelect);

    lblKSat.setText("Saturated conductivity");

    lblThetaSat.setText("Saturated moisture content");

    lblThetaInit.setText("Initial moisture content");

    btnKSatBrowse.setText("Browse");
    btnKSatBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnKSatBrowseActionPerformed(evt);
      }
    });

    btnThetaSatBrowse.setText("Browse");
    btnThetaSatBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnThetaSatBrowseActionPerformed(evt);
      }
    });

    btnThetaIniBrowse.setText("Browse");
    btnThetaIniBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnThetaIniBrowseActionPerformed(evt);
      }
    });

    btnNext1.setText("Next");
    btnNext1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNext1ActionPerformed(evt);
      }
    });

    lblInfilFile.setText("First infiltration file");

    txtInfilFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInfilFileActionPerformed(evt);
      }
    });

    btnInfilFileBrowse.setText("Browse");
    btnInfilFileBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnInfilFileBrowseActionPerformed(evt);
      }
    });

    lblPesticideFile.setText("File with pesticide application");

    lblFlowDirectionFile.setText("Flow direction file");

    btnPesticideFileBrowse.setText("Browse");
    btnPesticideFileBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPesticideFileBrowseActionPerformed(evt);
      }
    });

    btnFlowDirectionFileBrowse.setText("Browse");
    btnFlowDirectionFileBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFlowDirectionFileBrowseActionPerformed(evt);
      }
    });

    lblDEM.setText("Elevation map");

    txtDEM.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtDEMActionPerformed(evt);
      }
    });

    btnDEMBrowse.setText("Browse");
    btnDEMBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDEMBrowseActionPerformed(evt);
      }
    });

    lblSurfaceStorageFile.setText("First surf. water height file");

    btnSurfaceBrowse.setText("Browse");
    btnSurfaceBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSurfaceBrowseActionPerformed(evt);
      }
    });

    lblSurfaceVelocityFile.setText("First surf. water veloc. file");

    lblSurfaceRunoffFile.setText("First surf. water runoff file");

    btnSurfaceVelocityBrowse.setText("Browse");
    btnSurfaceVelocityBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSurfaceVelocityBrowseActionPerformed(evt);
      }
    });

    btnSurfaceRunoffBrowse.setText("Browse");
    btnSurfaceRunoffBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSurfaceRunoffBrowseActionPerformed(evt);
      }
    });

    lblPreipitationFile.setText("File with precipitation");

    btnPrecipitationFileBrowse.setText("Browse");
    btnPrecipitationFileBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPrecipitationFileBrowseActionPerformed(evt);
      }
    });

    lblPreipitationDataFile.setText("File with precipitation data");

    btnPrecipitationDataFileBrowse.setText("Browse");
    btnPrecipitationDataFileBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPrecipitationDataFileBrowseActionPerformed(evt);
      }
    });

    lblTimestep.setText("Lisem output interval (s)");

    lblDetachmentFile.setText("First sediment conc. file");

    btnDetachmentBrowse.setText("Browse");
    btnDetachmentBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDetachmentBrowseActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlLisemLayout = new javax.swing.GroupLayout(pnlLisem);
    pnlLisem.setLayout(pnlLisemLayout);
    pnlLisemLayout.setHorizontalGroup(
      pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLisemLayout.createSequentialGroup()
        .addContainerGap(277, Short.MAX_VALUE)
        .addComponent(lblTimestep)
        .addGap(18, 18, 18)
        .addComponent(txtTimestep, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(155, 155, 155)
        .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(pnlLisemLayout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblThetaInit)
          .addComponent(lblThetaSat)
          .addComponent(lblKSat)
          .addComponent(lblInfilFile)
          .addComponent(lblDEM)
          .addComponent(lblSurfaceStorageFile)
          .addComponent(lblSurfaceVelocityFile)
          .addComponent(lblSurfaceRunoffFile)
          .addComponent(lblFlowDirectionFile)
          .addComponent(lblDetachmentFile)
          .addComponent(lblPesticideFile)
          .addComponent(lblPreipitationFile)
          .addComponent(lblPreipitationDataFile))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtDEM, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
          .addComponent(txtKSat)
          .addComponent(txtThetaSat)
          .addComponent(txtThetaInit)
          .addComponent(txtInfilFile)
          .addComponent(txtSurfaceStorageFile)
          .addComponent(txtSurfaceVelocityFile)
          .addComponent(txtSurfaceRunoffFile)
          .addComponent(txtDetachmentFile)
          .addComponent(txtFlowDirectionFile)
          .addComponent(txtPrecipitationFile)
          .addComponent(txtPrecipitationDataFile)
          .addComponent(txtPesticideFile))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnPrecipitationDataFileBrowse)
          .addComponent(btnPesticideFileBrowse)
          .addComponent(btnPrecipitationFileBrowse)
          .addComponent(btnFlowDirectionFileBrowse)
          .addComponent(btnDetachmentBrowse)
          .addComponent(btnSurfaceRunoffBrowse)
          .addComponent(btnSurfaceVelocityBrowse)
          .addComponent(btnSurfaceBrowse)
          .addComponent(btnInfilFileBrowse)
          .addComponent(btnThetaIniBrowse)
          .addComponent(btnThetaSatBrowse)
          .addComponent(btnKSatBrowse)
          .addComponent(btnDEMBrowse))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlLisemLayout.setVerticalGroup(
      pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlLisemLayout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblDEM)
          .addComponent(txtDEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnDEMBrowse))
        .addGap(3, 3, 3)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblKSat)
          .addComponent(txtKSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnKSatBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtThetaSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblThetaSat)
          .addComponent(btnThetaSatBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblThetaInit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtThetaInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnThetaIniBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblInfilFile)
          .addComponent(txtInfilFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnInfilFileBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblSurfaceStorageFile)
          .addComponent(txtSurfaceStorageFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSurfaceBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtSurfaceVelocityFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblSurfaceVelocityFile)
          .addComponent(btnSurfaceVelocityBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblSurfaceRunoffFile)
          .addComponent(txtSurfaceRunoffFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSurfaceRunoffBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtDetachmentFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblDetachmentFile)
          .addComponent(btnDetachmentBrowse))
        .addGap(8, 8, 8)
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlLisemLayout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(lblFlowDirectionFile))
          .addGroup(pnlLisemLayout.createSequentialGroup()
            .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtFlowDirectionFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnFlowDirectionFileBrowse))
            .addGap(13, 13, 13)
            .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtPrecipitationFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnPrecipitationFileBrowse)
              .addComponent(lblPreipitationFile))
            .addGap(9, 9, 9)
            .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtPrecipitationDataFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnPrecipitationDataFileBrowse)
              .addComponent(lblPreipitationDataFile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtPesticideFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnPesticideFileBrowse)
              .addComponent(lblPesticideFile))))
        .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlLisemLayout.createSequentialGroup()
            .addGap(0, 30, Short.MAX_VALUE)
            .addComponent(btnNext1))
          .addGroup(pnlLisemLayout.createSequentialGroup()
            .addGroup(pnlLisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtTimestep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblTimestep))
            .addGap(0, 0, Short.MAX_VALUE))))
    );

    tbpnlMain.addTab("Lisem", pnlLisem);

    lblThetaFC.setText("Theta at FC");

    lblOutputDir.setText("Output dir");

    lblOrder.setText("Order file");

    chckbxNewArea.setSelected(true);
    chckbxNewArea.setText("New area");
    chckbxNewArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    lblOutputDepths.setText("Output depths:");

    chckbxDepth0.setSelected(true);
    chckbxDepth0.setText("Depth 1");
    chckbxDepth0.setEnabled(false);

    chckbxDepth1.setText("Depth 2");
    chckbxDepth1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth1ActionPerformed(evt);
      }
    });

    chckbxDepth2.setText("Depth 3");
    chckbxDepth2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth2ActionPerformed(evt);
      }
    });

    chckbxDepth3.setText("Depth 4");
    chckbxDepth3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth3ActionPerformed(evt);
      }
    });

    chckbxDepth4.setText("Depth 5");
    chckbxDepth4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth4ActionPerformed(evt);
      }
    });

    txtDepth4.setText("20");

    txtDepth3.setText("10");

    txtDepth2.setText("5");

    txtDepth1.setText("2");

    txtDepth0.setText("1");

    lblNewArea.setForeground(new java.awt.Color(255, 0, 0));
    lblNewArea.setText("If you made a run for this area before, uncheck this option. It saves time using existing files.");

    btnOrderFileBrowse.setText("Browse");
    btnOrderFileBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOrderFileBrowseActionPerformed(evt);
      }
    });

    btnOutputDirBrowse.setText("Browse");
    btnOutputDirBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOutputDirBrowseActionPerformed(evt);
      }
    });

    btnThetaFCBrowse.setText("Browse");
    btnThetaFCBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnThetaFCBrowseActionPerformed(evt);
      }
    });

    btnNext2.setText("Next");
    btnNext2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNext2ActionPerformed(evt);
      }
    });

    txtDepth9.setText("100");

    txtDepth8.setText("75");

    txtDepth7.setText("50");

    txtDepth6.setText("40");

    txtDepth5.setText("30");

    chckbxDepth9.setText("Depth 10");
    chckbxDepth9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth9ActionPerformed(evt);
      }
    });

    chckbxDepth8.setText("Depth 9");
    chckbxDepth8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth8ActionPerformed(evt);
      }
    });

    chckbxDepth7.setText("Depth 8");
    chckbxDepth7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth7ActionPerformed(evt);
      }
    });

    chckbxDepth6.setText("Depth 7");
    chckbxDepth6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth6ActionPerformed(evt);
      }
    });

    chckbxDepth5.setText("Depth 6");
    chckbxDepth5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxDepth5ActionPerformed(evt);
      }
    });

    lblLosses.setText("Losses");

    lblSegments.setText("Segments");

    btnLossesFileBrowse.setText("Browse");
    btnLossesFileBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLossesFileBrowseActionPerformed(evt);
      }
    });

    btnSegmentsFileBrowse.setText("Browse");
    btnSegmentsFileBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSegmentsFileBrowseActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlOutLayout = new javax.swing.GroupLayout(pnlOut);
    pnlOut.setLayout(pnlOutLayout);
    pnlOutLayout.setHorizontalGroup(
      pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlOutLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOutLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(pnlOutLayout.createSequentialGroup()
            .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblOutputDepths)
              .addGroup(pnlOutLayout.createSequentialGroup()
                .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth3)
                    .addGap(18, 18, 18)
                    .addComponent(txtDepth3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth2)
                    .addGap(18, 18, 18)
                    .addComponent(txtDepth2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth1)
                    .addGap(18, 18, 18)
                    .addComponent(txtDepth1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth4)
                    .addGap(18, 18, 18)
                    .addComponent(txtDepth4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(180, 180, 180)
                .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDepth5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDepth6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDepth7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDepth8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addComponent(chckbxDepth9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtDepth9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(pnlOutLayout.createSequentialGroup()
                .addComponent(chckbxDepth0)
                .addGap(18, 18, 18)
                .addComponent(txtDepth0, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(pnlOutLayout.createSequentialGroup()
                .addComponent(chckbxNewArea)
                .addGap(18, 18, 18)
                .addComponent(lblNewArea))
              .addGroup(pnlOutLayout.createSequentialGroup()
                .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lblOutputDir)
                  .addComponent(lblThetaFC)
                  .addComponent(lblOrder)
                  .addComponent(lblLosses)
                  .addComponent(lblSegments))
                .addGap(32, 32, 32)
                .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addComponent(txtThetaFC, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnThetaFCBrowse))
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addComponent(txtOutputDir, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnOutputDirBrowse))
                  .addGroup(pnlOutLayout.createSequentialGroup()
                    .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                      .addComponent(txtSegmentsFile, javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(txtLossesFile, javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(txtOrderFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(btnOrderFileBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(btnLossesFileBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(btnSegmentsFileBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGap(0, 31, Short.MAX_VALUE)))
        .addContainerGap())
    );
    pnlOutLayout.setVerticalGroup(
      pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlOutLayout.createSequentialGroup()
        .addGap(39, 39, 39)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtThetaFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblThetaFC)
          .addComponent(btnThetaFCBrowse))
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlOutLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(lblOutputDir))
          .addGroup(pnlOutLayout.createSequentialGroup()
            .addGap(9, 9, 9)
            .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtOutputDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnOutputDirBrowse))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblOrder)
          .addComponent(txtOrderFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnOrderFileBrowse))
        .addGap(9, 9, 9)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtLossesFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblLosses)
          .addComponent(btnLossesFileBrowse))
        .addGap(13, 13, 13)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblSegments)
          .addComponent(txtSegmentsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSegmentsFileBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(chckbxNewArea)
          .addComponent(lblNewArea))
        .addGap(18, 18, 18)
        .addComponent(lblOutputDepths, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(chckbxDepth0)
          .addComponent(chckbxDepth5)
          .addComponent(txtDepth5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtDepth0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(chckbxDepth1)
          .addComponent(chckbxDepth6)
          .addComponent(txtDepth6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtDepth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(chckbxDepth2)
          .addComponent(chckbxDepth7)
          .addComponent(txtDepth7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtDepth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(chckbxDepth3)
          .addComponent(chckbxDepth8)
          .addComponent(txtDepth8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtDepth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(chckbxDepth4)
          .addComponent(chckbxDepth9)
          .addComponent(txtDepth9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtDepth4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnNext2)
        .addContainerGap())
    );

    tbpnlMain.addTab("Output", pnlOut);

    lblCore.setText("Core");

    chckbxSurfaceOnly.setText("Only surface contents");

    btnCoreBrowse.setText("Browse");
    btnCoreBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCoreBrowseActionPerformed(evt);
      }
    });

    btnNextCore.setText("Next");
    btnNextCore.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNextCoreActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlCoreLayout = new javax.swing.GroupLayout(pnlCore);
    pnlCore.setLayout(pnlCoreLayout);
    pnlCoreLayout.setHorizontalGroup(
      pnlCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCoreLayout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(pnlCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(chckbxSurfaceOnly)
          .addGroup(pnlCoreLayout.createSequentialGroup()
            .addComponent(lblCore)
            .addGap(18, 18, 18)
            .addComponent(txtCore, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnCoreBrowse)))
        .addContainerGap(13, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoreLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnNextCore)
        .addContainerGap())
    );
    pnlCoreLayout.setVerticalGroup(
      pnlCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCoreLayout.createSequentialGroup()
        .addGap(56, 56, 56)
        .addGroup(pnlCoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCore)
          .addComponent(txtCore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCoreBrowse))
        .addGap(38, 38, 38)
        .addComponent(chckbxSurfaceOnly)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 431, Short.MAX_VALUE)
        .addComponent(btnNextCore)
        .addContainerGap())
    );

    tbpnlMain.addTab("Core", pnlCore);

    btnNext3.setText("Next");
    btnNext3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNext3ActionPerformed(evt);
      }
    });

    lblProfileDepth.setText("Profile depth (cm)");

    txtProfileDepth.setText("150");

    lblInitialConcentration.setText("Initial concentration");

    lblAppliedConcentration.setText("Applied concentration");

    lblRetardataionFactor.setText("Retardation factor");

    lblDispersionCoefficient.setText("Dispersion coefficient");

    lblDegradationCoefficient.setText("Degradation coefficient");

    txtDegradationCoefficient.setText("0.0001");

    txtDispersionCoefficient.setText("0.0001");

    txtRetardationFactor.setText("0.0001");

    txtAppliedConcentration.setText("0.0001");

    txtInitialConcentration.setText("0.0001");

    lblTimeSteps.setText("Time steps");

    txtTimeSteps.setText("999");

    lblHalfTime.setText("Half time(min)");

    txtHalfTime.setText("10");

    lblMaxCw.setText("Max conc. in water");

    lblMaxCs.setText("Max conc. in soil");

    txtMaxCw.setText("-1");

    txtMaxCs.setText("-1");

    lblInitialCellContent.setText("Initial cell content (ug)");

    txtInitialCellContent.setText("-1");

    lblInfiltrationFactor.setText("Infiltration factor");

    txtInfiltrationFactor.setText("-1");

    javax.swing.GroupLayout pnlPesticideLayout = new javax.swing.GroupLayout(pnlPesticide);
    pnlPesticide.setLayout(pnlPesticideLayout);
    pnlPesticideLayout.setHorizontalGroup(
      pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesticideLayout.createSequentialGroup()
        .addContainerGap(706, Short.MAX_VALUE)
        .addComponent(btnNext3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(pnlPesticideLayout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesticideLayout.createSequentialGroup()
              .addComponent(lblDegradationCoefficient)
              .addGap(18, 18, 18))
            .addGroup(pnlPesticideLayout.createSequentialGroup()
              .addComponent(lblDispersionCoefficient)
              .addGap(28, 28, 28)))
          .addGroup(pnlPesticideLayout.createSequentialGroup()
            .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblRetardataionFactor)
              .addComponent(lblAppliedConcentration)
              .addComponent(lblInitialConcentration)
              .addComponent(lblProfileDepth)
              .addComponent(lblTimeSteps)
              .addComponent(lblHalfTime))
            .addGap(26, 26, 26)))
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtProfileDepth)
          .addComponent(txtInitialConcentration)
          .addComponent(txtAppliedConcentration)
          .addComponent(txtRetardationFactor)
          .addComponent(txtDispersionCoefficient)
          .addComponent(txtDegradationCoefficient)
          .addComponent(txtTimeSteps)
          .addComponent(txtHalfTime))
        .addGap(223, 223, 223)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblMaxCw)
          .addComponent(lblMaxCs)
          .addComponent(lblInitialCellContent)
          .addComponent(lblInfiltrationFactor))
        .addGap(20, 20, 20)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtInfiltrationFactor, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
          .addComponent(txtMaxCw, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
          .addComponent(txtMaxCs)
          .addComponent(txtInitialCellContent))
        .addContainerGap(27, Short.MAX_VALUE))
    );
    pnlPesticideLayout.setVerticalGroup(
      pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesticideLayout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblProfileDepth)
          .addComponent(txtProfileDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblMaxCw)
          .addComponent(txtMaxCw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(23, 23, 23)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblInitialConcentration)
          .addComponent(txtInitialConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblMaxCs)
          .addComponent(txtMaxCs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblAppliedConcentration)
          .addComponent(txtAppliedConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblInfiltrationFactor)
          .addComponent(txtInfiltrationFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(45, 45, 45)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblRetardataionFactor)
          .addComponent(txtRetardationFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblDispersionCoefficient)
          .addComponent(txtDispersionCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblDegradationCoefficient)
          .addComponent(txtDegradationCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(24, 24, 24)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblHalfTime)
          .addComponent(txtHalfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblInitialCellContent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtInitialCellContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(23, 23, 23)
        .addGroup(pnlPesticideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTimeSteps)
          .addComponent(txtTimeSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
        .addComponent(btnNext3)
        .addContainerGap())
    );

    tbpnlMain.addTab("Pesticide", pnlPesticide);

    lblWaterVelocity.setText("Water velocity");

    lblTopConcentration.setText("concentration at the top");

    txtWaterVelocity.setText("jTextField1");

    txtTopConcentration.setText("jTextField1");

    lblOutputSingleRun.setText("Output file");

    txtOutputFileSingleRun.setText("jTextField1");

    btnBrowseOutputSingleRun.setText("...");
    btnBrowseOutputSingleRun.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBrowseOutputSingleRunActionPerformed(evt);
      }
    });

    btnNext5.setText("Next");
    btnNext5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNext5ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlSingleRunLayout = new javax.swing.GroupLayout(pnlSingleRun);
    pnlSingleRun.setLayout(pnlSingleRunLayout);
    pnlSingleRunLayout.setHorizontalGroup(
      pnlSingleRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlSingleRunLayout.createSequentialGroup()
        .addGap(58, 58, 58)
        .addGroup(pnlSingleRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblTopConcentration)
          .addComponent(lblOutputSingleRun)
          .addComponent(lblWaterVelocity))
        .addGap(33, 33, 33)
        .addGroup(pnlSingleRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtWaterVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtTopConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(pnlSingleRunLayout.createSequentialGroup()
            .addComponent(txtOutputFileSingleRun, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnBrowseOutputSingleRun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(84, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSingleRunLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnNext5)
        .addContainerGap())
    );
    pnlSingleRunLayout.setVerticalGroup(
      pnlSingleRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlSingleRunLayout.createSequentialGroup()
        .addGap(53, 53, 53)
        .addGroup(pnlSingleRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblWaterVelocity)
          .addComponent(txtWaterVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(28, 28, 28)
        .addGroup(pnlSingleRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTopConcentration)
          .addComponent(txtTopConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(56, 56, 56)
        .addGroup(pnlSingleRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblOutputSingleRun)
          .addComponent(txtOutputFileSingleRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBrowseOutputSingleRun))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
        .addComponent(btnNext5)
        .addContainerGap())
    );

    tbpnlMain.addTab("Single", pnlSingleRun);

    txtLog.setColumns(20);
    txtLog.setRows(5);
    scrlpnLog.setViewportView(txtLog);

    lblLog.setText("jLabel1");

    javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
    pnlLog.setLayout(pnlLogLayout);
    pnlLogLayout.setHorizontalGroup(
      pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrlpnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(lblLog)
        .addContainerGap(65, Short.MAX_VALUE))
    );
    pnlLogLayout.setVerticalGroup(
      pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlLogLayout.createSequentialGroup()
        .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(pnlLogLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(scrlpnLog, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
          .addGroup(pnlLogLayout.createSequentialGroup()
            .addGap(54, 54, 54)
            .addComponent(lblLog)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );

    tbpnlMain.addTab("Log", pnlLog);

    btnExit.setText("Exit");
    btnExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExitActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(tbpnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(tbpnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnExit))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnExitActionPerformed

  private void btnNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext3ActionPerformed
    txtLog.setText("");
    myControl.storePesticideData(txtTimeSteps, txtProfileDepth, txtInitialConcentration,
      txtAppliedConcentration, txtRetardationFactor, txtDispersionCoefficient,
      txtDegradationCoefficient, txtHalfTime, txtMaxCw, txtMaxCs, txtInfiltrationFactor, 
      txtInitialCellContent);
    if (myControl.singleRun){
      tbpnlMain.setSelectedIndex(5);
    }
    else
    {
      tbpnlMain.setSelectedIndex(6);
      myTimer = new Timer();
      Integer mSec = 1000;
      myTimer.schedule(new TimerReaction(), mSec, mSec);
      myControl.start();
      myTimer.cancel();
    }
  }//GEN-LAST:event_btnNext3ActionPerformed

  private void btnInfilFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfilFileBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtInfilFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnInfilFileBrowseActionPerformed

  private void txtInfilFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfilFileActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtInfilFileActionPerformed

  private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
    myControl.storeLisemFileNames(txtDEM, txtKSat, txtThetaSat, txtThetaInit, txtInfilFile, 
            txtFlowDirectionFile, txtPesticideFile, txtSurfaceStorageFile, txtSurfaceVelocityFile,
            txtSurfaceRunoffFile, txtDetachmentFile, txtPrecipitationFile, txtPrecipitationDataFile, txtTimestep);
    tbpnlMain.setSelectedIndex(2);
  }//GEN-LAST:event_btnNext1ActionPerformed

  private void btnThetaIniBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThetaIniBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtThetaInit.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnThetaIniBrowseActionPerformed

  private void btnThetaSatBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThetaSatBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtThetaSat.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnThetaSatBrowseActionPerformed

  private void btnKSatBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKSatBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtKSat.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnKSatBrowseActionPerformed

  private void btnLisemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLisemActionPerformed
    tbpnlMain.setSelectedIndex(1);
    myControl.singleRun = false;
  }//GEN-LAST:event_btnLisemActionPerformed

  private void btnSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingleActionPerformed
    myControl.singleRun = true;
    tbpnlMain.setSelectedIndex(4);
  }//GEN-LAST:event_btnSingleActionPerformed

  private void btnBrowseOutputSingleRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseOutputSingleRunActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtOutputFileSingleRun.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnBrowseOutputSingleRunActionPerformed

  private void btnNext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext5ActionPerformed
    myControl.storeSingleRun(txtTopConcentration, txtWaterVelocity, txtOutputFileSingleRun);
    tbpnlMain.setSelectedIndex(6);
    myTimer = new Timer();
    Integer mSec = 1000;
    myTimer.schedule(new TimerReaction(), mSec, mSec);
    myControl.start();
    myTimer.cancel();
  }//GEN-LAST:event_btnNext5ActionPerformed

  private void btnPesticideFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesticideFileBrowseActionPerformed
   JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtPesticideFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnPesticideFileBrowseActionPerformed

  private void btnFlowDirectionFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlowDirectionFileBrowseActionPerformed
     JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtFlowDirectionFile.setText(myDialog.getSelectedFile().toString());
    }
  // TODO add your handling code here:
  }//GEN-LAST:event_btnFlowDirectionFileBrowseActionPerformed

  private void txtDEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDEMActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtDEMActionPerformed

  private void btnDEMBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEMBrowseActionPerformed
    // TODO add your handling code here:
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtDEM.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnDEMBrowseActionPerformed

  private void btnSurfaceBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurfaceBrowseActionPerformed
    // TODO add your handling code here:
   JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtSurfaceStorageFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnSurfaceBrowseActionPerformed

  private void chckbxDepth5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth5ActionPerformed
    txtDepth5.setEnabled(chckbxDepth5.isSelected());
    chckbxDepth6.setSelected(false);
    chckbxDepth6.setEnabled(chckbxDepth5.isSelected());
    txtDepth6.setEnabled(false);
    chckbxDepth7.setSelected(false);
    chckbxDepth7.setEnabled(false);
    txtDepth7.setEnabled(false);
    chckbxDepth8.setSelected(false);
    chckbxDepth8.setEnabled(false);
    txtDepth8.setEnabled(false);
    chckbxDepth9.setSelected(false);
    chckbxDepth9.setEnabled(false);
    txtDepth9.setEnabled(false);
  }//GEN-LAST:event_chckbxDepth5ActionPerformed

  private void chckbxDepth6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth6ActionPerformed
    txtDepth6.setEnabled(chckbxDepth6.isSelected());
    chckbxDepth7.setSelected(false);
    chckbxDepth7.setEnabled(chckbxDepth6.isSelected());
    txtDepth7.setEnabled(false);
    chckbxDepth8.setSelected(false);
    chckbxDepth8.setEnabled(false);
    txtDepth8.setEnabled(false);
    chckbxDepth9.setSelected(false);
    chckbxDepth9.setEnabled(false);
    txtDepth9.setEnabled(false);
  }//GEN-LAST:event_chckbxDepth6ActionPerformed

  private void chckbxDepth7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth7ActionPerformed
    txtDepth7.setEnabled(chckbxDepth7.isSelected());
    chckbxDepth8.setSelected(false);
    chckbxDepth8.setEnabled(chckbxDepth7.isSelected());
    txtDepth8.setEnabled(false);
    chckbxDepth9.setSelected(false);
    chckbxDepth9.setEnabled(false);
    txtDepth9.setEnabled(false);
  }//GEN-LAST:event_chckbxDepth7ActionPerformed

  private void chckbxDepth8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth8ActionPerformed
    txtDepth8.setEnabled(chckbxDepth8.isSelected());
    chckbxDepth9.setSelected(false);
    chckbxDepth9.setEnabled(chckbxDepth8.isSelected());
    txtDepth9.setEnabled(false);
  }//GEN-LAST:event_chckbxDepth8ActionPerformed

  private void chckbxDepth9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth9ActionPerformed
    txtDepth9.setEnabled(chckbxDepth9.isSelected());
  }//GEN-LAST:event_chckbxDepth9ActionPerformed

  private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
    myControl.storeOutputFilesAndDepths(txtOutputDir, txtThetaFC, txtOrderFile, txtLossesFile, txtSegmentsFile,
      chckbxDepth0, chckbxDepth1, chckbxDepth2, chckbxDepth3, chckbxDepth4,
      chckbxDepth5, chckbxDepth6, chckbxDepth7, chckbxDepth8, chckbxDepth9,
      txtDepth0, txtDepth1, txtDepth2, txtDepth3, txtDepth4,
      txtDepth5, txtDepth6, txtDepth7, txtDepth8, txtDepth9,
      chckbxNewArea);
    tbpnlMain.setSelectedIndex(3);
  }//GEN-LAST:event_btnNext2ActionPerformed

  private void btnThetaFCBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThetaFCBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtThetaFC.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnThetaFCBrowseActionPerformed

  private void btnOutputDirBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutputDirBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    myDialog.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtOutputDir.setText(myDialog.getSelectedFile().toString());
    }
    // TODO add your handling code here:
  }//GEN-LAST:event_btnOutputDirBrowseActionPerformed

  private void btnOrderFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderFileBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtOrderFile.setText(myDialog.getSelectedFile().toString());
    }
    // TODO add your handling code here:
  }//GEN-LAST:event_btnOrderFileBrowseActionPerformed

  private void chckbxDepth4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth4ActionPerformed
    txtDepth4.setEnabled(chckbxDepth4.isSelected());
    chckbxDepth5.setSelected(false);
    chckbxDepth5.setEnabled(chckbxDepth4.isSelected());
    txtDepth5.setEnabled(false);
    chckbxDepth6.setSelected(false);
    chckbxDepth6.setEnabled(false);
    txtDepth6.setEnabled(false);
    chckbxDepth7.setSelected(false);
    chckbxDepth7.setEnabled(false);
    txtDepth7.setEnabled(false);
    chckbxDepth8.setSelected(false);
    chckbxDepth8.setEnabled(false);
    txtDepth8.setEnabled(false);
    chckbxDepth9.setSelected(false);
    chckbxDepth9.setEnabled(false);
    txtDepth9.setEnabled(false);
  }//GEN-LAST:event_chckbxDepth4ActionPerformed

  private void chckbxDepth3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth3ActionPerformed
    txtDepth3.setEnabled(chckbxDepth3.isSelected());
    chckbxDepth4.setSelected(false);
    chckbxDepth4.setEnabled(chckbxDepth3.isSelected());
    txtDepth4.setEnabled(false);
    chckbxDepth5.setSelected(false);
    chckbxDepth5.setEnabled(false);
    txtDepth5.setEnabled(false);
    chckbxDepth6.setSelected(false);
    chckbxDepth6.setEnabled(false);
    txtDepth6.setEnabled(false);
    chckbxDepth7.setSelected(false);
    chckbxDepth7.setEnabled(false);
    txtDepth7.setEnabled(false);
    chckbxDepth8.setSelected(false);
    chckbxDepth8.setEnabled(false);
    txtDepth8.setEnabled(false);
    chckbxDepth9.setSelected(false);
    chckbxDepth9.setEnabled(false);
    txtDepth9.setEnabled(false);
  }//GEN-LAST:event_chckbxDepth3ActionPerformed

  private void chckbxDepth2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth2ActionPerformed
    txtDepth2.setEnabled(chckbxDepth2.isSelected());
    chckbxDepth3.setSelected(false);
    chckbxDepth3.setEnabled(chckbxDepth2.isSelected());
    txtDepth3.setEnabled(false);
    chckbxDepth4.setSelected(false);
    chckbxDepth4.setEnabled(false);
    txtDepth4.setEnabled(false);
    chckbxDepth5.setSelected(false);
    chckbxDepth5.setEnabled(false);
    txtDepth5.setEnabled(false);
    chckbxDepth6.setSelected(false);
    chckbxDepth6.setEnabled(false);
    txtDepth6.setEnabled(false);
    chckbxDepth7.setSelected(false);
    chckbxDepth7.setEnabled(false);
    txtDepth7.setEnabled(false);
    chckbxDepth8.setSelected(false);
    chckbxDepth8.setEnabled(false);
    txtDepth8.setEnabled(false);
    chckbxDepth9.setSelected(false);
    chckbxDepth9.setEnabled(false);
    txtDepth9.setEnabled(false);
  }//GEN-LAST:event_chckbxDepth2ActionPerformed

  private void chckbxDepth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxDepth1ActionPerformed
    txtDepth1.setEnabled(chckbxDepth1.isSelected());
    chckbxDepth2.setSelected(false);
    chckbxDepth2.setEnabled(chckbxDepth1.isSelected());
    txtDepth2.setEnabled(false);
    chckbxDepth3.setSelected(false);
    chckbxDepth3.setEnabled(false);
    txtDepth3.setEnabled(false);
    chckbxDepth4.setSelected(false);
    chckbxDepth4.setEnabled(false);
    txtDepth4.setEnabled(false);
    chckbxDepth5.setSelected(false);
    chckbxDepth5.setEnabled(false);
    txtDepth5.setEnabled(false);
    chckbxDepth6.setSelected(false);
    chckbxDepth6.setEnabled(false);
    txtDepth6.setEnabled(false);
    chckbxDepth7.setSelected(false);
    chckbxDepth7.setEnabled(false);
    txtDepth7.setEnabled(false);
    chckbxDepth8.setSelected(false);
    chckbxDepth8.setEnabled(false);
    txtDepth8.setEnabled(false);
    chckbxDepth9.setSelected(false);
    chckbxDepth9.setEnabled(false);
    txtDepth9.setEnabled(false);
  }//GEN-LAST:event_chckbxDepth1ActionPerformed

  private void btnSurfaceVelocityBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurfaceVelocityBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtSurfaceVelocityFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnSurfaceVelocityBrowseActionPerformed

  private void btnSurfaceRunoffBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurfaceRunoffBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtSurfaceRunoffFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnSurfaceRunoffBrowseActionPerformed

  private void btnPrecipitationFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecipitationFileBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtPrecipitationFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnPrecipitationFileBrowseActionPerformed

  private void btnPrecipitationDataFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecipitationDataFileBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtPrecipitationDataFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnPrecipitationDataFileBrowseActionPerformed

  private void btnDetachmentBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetachmentBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtDetachmentFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnDetachmentBrowseActionPerformed

  private void btnLossesFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLossesFileBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtLossesFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnLossesFileBrowseActionPerformed

  private void btnSegmentsFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegmentsFileBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtSegmentsFile.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnSegmentsFileBrowseActionPerformed

  private void btnCoreBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoreBrowseActionPerformed
    JFileChooser myDialog = new JFileChooser();
    int result = myDialog.showOpenDialog(null);
    if (result==JFileChooser.APPROVE_OPTION ) {
      txtCore.setText(myDialog.getSelectedFile().toString());
    }
  }//GEN-LAST:event_btnCoreBrowseActionPerformed

  private void btnNextCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextCoreActionPerformed
   myControl.storeCoreData(txtCore, chckbxSurfaceOnly);
   tbpnlMain.setSelectedIndex(4);
  }//GEN-LAST:event_btnNextCoreActionPerformed

  private void setFieldVisibility(){
    if (!chckbxDepth1.isSelected()){
      chckbxDepth1ActionPerformed(null);
    }
    else
    {
      if (!chckbxDepth2.isSelected()){
        chckbxDepth2ActionPerformed(null);
      }
      else
      {
        if (!chckbxDepth3.isSelected()){
          chckbxDepth3ActionPerformed(null);
        }
        else
        {
          if (!chckbxDepth4.isSelected()){
            chckbxDepth4ActionPerformed(null);
          }
          else
          {
            if (!chckbxDepth5.isSelected()){
              chckbxDepth5ActionPerformed(null);
            }
            else
            {
              if (!chckbxDepth6.isSelected()){
                chckbxDepth6ActionPerformed(null);
              }
              else
              {
                if (!chckbxDepth7.isSelected()){
                  chckbxDepth7ActionPerformed(null);
                }
                else
                {
                  if (!chckbxDepth8.isSelected()){
                    chckbxDepth8ActionPerformed(null);
                  }
                  else
                  {
                    if (!chckbxDepth9.isSelected()){
                      chckbxDepth9ActionPerformed(null);
                    }
                  }
                }      
              } 
            } 
          } 
        } 
      } 
    }
  }
  
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(PestPostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(PestPostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(PestPostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(PestPostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PestPostGUI().setVisible(true);
      }
    });
  }

      public class AddToLogEventListener implements AddToLogEventClassListener {
      // ... code here

      //implement the required method(s) of the interface
       @Override
       public void handleAddToLogEventClassEvent(AddToLogEventClass evt) {
        txtLog.append(myControl.logLine);
        txtLog.repaint();
//        lblLog.setText(myControl.logLine);
        lblLog.revalidate();
        txtLog.revalidate();
        txtLog.repaint();
        pnlLog.revalidate();
       }
    }

    class TimerReaction extends TimerTask {
      @Override
      public void run() {
        revalidate();
        repaint();
      }
    }
 
   
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBrowseOutputSingleRun;
  private javax.swing.JButton btnCoreBrowse;
  private javax.swing.JButton btnDEMBrowse;
  private javax.swing.JButton btnDetachmentBrowse;
  private javax.swing.JButton btnExit;
  private javax.swing.JButton btnFlowDirectionFileBrowse;
  private javax.swing.JButton btnInfilFileBrowse;
  private javax.swing.JButton btnKSatBrowse;
  private javax.swing.JButton btnLisem;
  private javax.swing.JButton btnLossesFileBrowse;
  private javax.swing.JButton btnNext1;
  private javax.swing.JButton btnNext2;
  private javax.swing.JButton btnNext3;
  private javax.swing.JButton btnNext5;
  private javax.swing.JButton btnNextCore;
  private javax.swing.JButton btnOrderFileBrowse;
  private javax.swing.JButton btnOutputDirBrowse;
  private javax.swing.JButton btnPesticideFileBrowse;
  private javax.swing.JButton btnPrecipitationDataFileBrowse;
  private javax.swing.JButton btnPrecipitationFileBrowse;
  private javax.swing.JButton btnSegmentsFileBrowse;
  private javax.swing.JButton btnSingle;
  private javax.swing.JButton btnSurfaceBrowse;
  private javax.swing.JButton btnSurfaceRunoffBrowse;
  private javax.swing.JButton btnSurfaceVelocityBrowse;
  private javax.swing.JButton btnThetaFCBrowse;
  private javax.swing.JButton btnThetaIniBrowse;
  private javax.swing.JButton btnThetaSatBrowse;
  private javax.swing.JCheckBox chckbxDepth0;
  private javax.swing.JCheckBox chckbxDepth1;
  private javax.swing.JCheckBox chckbxDepth2;
  private javax.swing.JCheckBox chckbxDepth3;
  private javax.swing.JCheckBox chckbxDepth4;
  private javax.swing.JCheckBox chckbxDepth5;
  private javax.swing.JCheckBox chckbxDepth6;
  private javax.swing.JCheckBox chckbxDepth7;
  private javax.swing.JCheckBox chckbxDepth8;
  private javax.swing.JCheckBox chckbxDepth9;
  private javax.swing.JCheckBox chckbxNewArea;
  private javax.swing.JCheckBox chckbxSurfaceOnly;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JLabel lblAppliedConcentration;
  private javax.swing.JLabel lblCore;
  private javax.swing.JLabel lblDEM;
  private javax.swing.JLabel lblDegradationCoefficient;
  private javax.swing.JLabel lblDetachmentFile;
  private javax.swing.JLabel lblDispersionCoefficient;
  private javax.swing.JLabel lblFlowDirectionFile;
  private javax.swing.JLabel lblHalfTime;
  private javax.swing.JLabel lblInfilFile;
  private javax.swing.JLabel lblInfiltrationFactor;
  private javax.swing.JLabel lblInitialCellContent;
  private javax.swing.JLabel lblInitialConcentration;
  private javax.swing.JLabel lblKSat;
  private javax.swing.JLabel lblLog;
  private javax.swing.JLabel lblLosses;
  private javax.swing.JLabel lblMaxCs;
  private javax.swing.JLabel lblMaxCw;
  private javax.swing.JLabel lblNewArea;
  private javax.swing.JLabel lblOrder;
  private javax.swing.JLabel lblOutputDepths;
  private javax.swing.JLabel lblOutputDir;
  private javax.swing.JLabel lblOutputSingleRun;
  private javax.swing.JLabel lblPesticideFile;
  private javax.swing.JLabel lblPreipitationDataFile;
  private javax.swing.JLabel lblPreipitationFile;
  private javax.swing.JLabel lblProfileDepth;
  private javax.swing.JLabel lblRetardataionFactor;
  private javax.swing.JLabel lblSegments;
  private javax.swing.JLabel lblSurfaceRunoffFile;
  private javax.swing.JLabel lblSurfaceStorageFile;
  private javax.swing.JLabel lblSurfaceVelocityFile;
  private javax.swing.JLabel lblThetaFC;
  private javax.swing.JLabel lblThetaInit;
  private javax.swing.JLabel lblThetaSat;
  private javax.swing.JLabel lblTimeSteps;
  private javax.swing.JLabel lblTimestep;
  private javax.swing.JLabel lblTopConcentration;
  private javax.swing.JLabel lblWaterVelocity;
  private javax.swing.JPanel pnlCore;
  private javax.swing.JPanel pnlLisem;
  private javax.swing.JPanel pnlLog;
  private javax.swing.JPanel pnlOut;
  private javax.swing.JPanel pnlPesticide;
  private javax.swing.JPanel pnlSelect;
  private javax.swing.JPanel pnlSingleRun;
  private javax.swing.JScrollPane scrlpnLog;
  private javax.swing.JTabbedPane tbpnlMain;
  private javax.swing.JTextField txtAppliedConcentration;
  private javax.swing.JTextField txtCore;
  private javax.swing.JTextField txtDEM;
  private javax.swing.JTextField txtDegradationCoefficient;
  private javax.swing.JTextField txtDepth0;
  private javax.swing.JTextField txtDepth1;
  private javax.swing.JTextField txtDepth2;
  private javax.swing.JTextField txtDepth3;
  private javax.swing.JTextField txtDepth4;
  private javax.swing.JTextField txtDepth5;
  private javax.swing.JTextField txtDepth6;
  private javax.swing.JTextField txtDepth7;
  private javax.swing.JTextField txtDepth8;
  private javax.swing.JTextField txtDepth9;
  private javax.swing.JTextField txtDetachmentFile;
  private javax.swing.JTextField txtDispersionCoefficient;
  private javax.swing.JTextField txtFlowDirectionFile;
  private javax.swing.JTextField txtHalfTime;
  private javax.swing.JTextField txtInfilFile;
  private javax.swing.JTextField txtInfiltrationFactor;
  private javax.swing.JTextField txtInitialCellContent;
  private javax.swing.JTextField txtInitialConcentration;
  private javax.swing.JTextField txtKSat;
  private javax.swing.JTextArea txtLog;
  private javax.swing.JTextField txtLossesFile;
  private javax.swing.JTextField txtMaxCs;
  private javax.swing.JTextField txtMaxCw;
  private javax.swing.JTextField txtOrderFile;
  private javax.swing.JTextField txtOutputDir;
  private javax.swing.JTextField txtOutputFileSingleRun;
  private javax.swing.JTextField txtPesticideFile;
  private javax.swing.JTextField txtPrecipitationDataFile;
  private javax.swing.JTextField txtPrecipitationFile;
  private javax.swing.JTextField txtProfileDepth;
  private javax.swing.JTextField txtRetardationFactor;
  private javax.swing.JTextField txtSegmentsFile;
  private javax.swing.JTextField txtSurfaceRunoffFile;
  private javax.swing.JTextField txtSurfaceStorageFile;
  private javax.swing.JTextField txtSurfaceVelocityFile;
  private javax.swing.JTextField txtThetaFC;
  private javax.swing.JTextField txtThetaInit;
  private javax.swing.JTextField txtThetaSat;
  private javax.swing.JTextField txtTimeSteps;
  private javax.swing.JTextField txtTimestep;
  private javax.swing.JTextField txtTopConcentration;
  private javax.swing.JTextField txtWaterVelocity;
  // End of variables declaration//GEN-END:variables
}
